
exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', 'vendor', 'node_modules', '_assets', 'mix-manifest.json', 'webpack.mix.js',
  'assets/css/main-bundle.css',
  'assets/js/main-bundle.js',
]
